version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=northwindpw
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MSSQL_SA_PASSWORD=N0rthw1ndpw
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
    ports: 
      - 1433:1433  
    volumes:
      - /var/lib/microsoftssql/data 